Repository johannesgrothe/Smarthome_Bridge, pull requests merged in 2021-12, with the labels that each got.

#49 Fb 46 gadget manager characteristic update
  gadget_publishers/gadget_publisher.py
  gadget_publishers/gadget_publisher_homebridge.py
  gadget_publishers/homebridge_encoder.py
  gadget_publishers/homebridge_network_connector.py
  gadgets/gadget_factory.py
  gadgets/lamp_neopixel_basic.py
  network/mqtt_connector.py
  network/mqtt_server_client.py
  smarthome_bridge/api_decoder.py
  smarthome_bridge/api_manager.py
  smarthome_bridge/api_manager_delegate.py
  smarthome_bridge/bridge.py
  smarthome_bridge/bridge_main.py
  smarthome_bridge/gadget_manager.py
  smarthome_bridge/gadget_pubsub.py
  smarthome_bridge/gadget_status_supplier.py
  smarthome_bridge/gadget_update_information.py
  test_helpers/dummy_api_delegate.py
  test_helpers/gadget_fixtures.py
  tests/bridge/gadget_publishers/test_gadget_publisher_homebridge.py
  tests/bridge/gadget_publishers/test_homebridge_encoder.py
  tests/bridge/gadgets/test_gadget_factory.py
  tests/bridge/test_api_manager.py
Labels: enhancement

#52 #50 Updated Workflow
  .github/workflows/repo_checks.yml
Labels: repository

#55 #54 Added workaround for github actions bug
  .github/workflows/repo_checks.yml
Labels: bug

#56 #51 Switched to gadget definition from system submodule
  gadget_publishers/gadget_publisher_homebridge.py
  gadget_publishers/homebridge_encoder.py
  gadgetlib.py
  gadgets/any_gadget.py
  gadgets/fan.py
  gadgets/gadget.py
  gadgets/gadget_factory.py
  gadgets/lamp.py
  smarthome_bridge/api_decoder.py
  smarthome_bridge/api_encoder.py
  smarthome_bridge/characteristic.py
  smarthome_bridge/gadget_update_information.py
  test_helpers/gadget_fixtures.py
  tests/bridge/gadget_publishers/test_homebridge_decoder.py
  tests/bridge/gadget_publishers/test_homebridge_encoder.py
  tests/bridge/gadgets/test_gadget.py
  tests/bridge/gadgets/test_gadget_factory.py
  tests/bridge/gadgets/test_gadgetlib.py
  tests/bridge/test_api_encoder_decoder.py
  tests/bridge/test_api_manager.py
  tests/bridge/test_characteristic.py
Labels: enhancement

#57 Fb 43 add issue templates
  .github/issue_template/bug.yml
  .github/issue_template/change.yml
  .github/issue_template/feature.yml
Labels: repository

#60 #59 Renamed issue template folder
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: bug
